import type { Metadata } from "next";
import Countries from "@/components/countries/countries";
import style from "./page.module.sass"
import Inputs from "@/components/inputs/inputs";

export const metadata: Metadata = {
  title: "Countries API | GC",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section className={style.page}>
      <Inputs />
      <Countries />
    </section>
  );
}
